---

sys_defaults:
  - domain: .GlobalPreferences
    key: com.apple.mouse.scaling
    type: string
    value: -1

  - domain: .GlobalPreferences
    key: com.apple.scrollwheel.scaling
    type: string
    value: -1

  - domain: com.apple.TextEdit
    key: TabWidth
    type: string
    value: 4


core_apps:
  - onyx
  - firefox
  - keka
