---
## GLOBAL ##
_zsh_dir_: "{{ _xdg_conf_home_ }}/zsh"
_omz_dir_: "{{ _zsh_dir_  }}/oh-my-zsh"
## GLOBAL ##

packages:
  - git
  - zsh

git_repos:
  - src: "https://github.com/romkatv/powerlevel10k"
    dest: "{{ _zsh_dir_ }}/powerlevel10k"

  - src: "https://github.com/zsh-users/zsh-syntax-highlighting"
    dest: "{{ _zsh_dir_ }}/zsh-syntax-highlighting"

  - src: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ _zsh_dir_ }}/zsh-autosuggestions"

  - src: "https://github.com/zsh-users/zsh-history-substring-search"
    dest: "{{ _zsh_dir_ }}/zsh-history-substring-search"

  - src: "https://github.com/junegunn/fzf.git"
    dest: "{{ _zsh_dir_  }}/fzf"

  - src: "https://github.com/Aloxaf/fzf-tab.git"
    dest: "{{ _zsh_dir_ }}/fzf-tab"

  - src: "https://github.com/rupa/z.git"
    dest: "{{ _zsh_dir_ }}/z"

  - src: "https://github.com/seebi/dircolors-solarized"
    dest: "{{ _zsh_dir_ }}/dircolors-solarized"

  - src: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ _xdg_data_home_ }}/asdf"

  - src: "https://github.com/dylanaraps/fff"
    dest: "{{ _zsh_dir_ }}/fff"

  - src: "https://github.com/cyproterone/tmux.git"
    dest: "{{ _xdg_conf_home_ }}/tmux"

  - src: "https://github.com/ms-jpq/isomorphic-copy.git"
    dest: "{{ _xdg_conf_home_ }}/isomorphic-copy"

  - src: "https://github.com/cyproterone/nvim2.git"
    dest: "{{ _xdg_conf_home_ }}/nvim"

target_files:
  - src: "home/"
    dest: "~/"

  - src: "zsh/"
    dest: "{{ _zsh_dir_ }}/rc"
    delete: True

target_templates:
  - src: "templates/home/"
    dest: "~/"

target_touches:
  - "~/.ssh/config"
  - "{{ _xdg_conf_home_ }}/git/config"
  - "{{ _xdg_cache_home_ }}/zz"

git_conf:
  pull.rebase: True
  diff.algorithm: minimal

  delta.light: True

target_lines:
  - file: "~/.ssh/config"
    line: "ServerAliveInterval 1"
  - file: "~/.ssh/config"
    line: "ServerAliveCountMax 5"

target_links: []
